name:                NbodyProblem1
version:             0.1.0.0
github:              "MamedovAR/NbodyProblem_1"
license:             LGPL-3
author:              "Artem Mamedov"
maintainer:          "a.mamedov1@g.nsu.ru"
copyright:           "2023 Artem Mamedov"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/NbodyProblem1#readme>

dependencies:
- base >= 4.7 && < 5
- GLUT
- OpenGL
- QuickCheck

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src/NBodyProblem

executables:
  NbodyProblem1-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - NbodyProblem1
    - GLUT
    - OpenGL

tests:
  NbodyProblem1-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - NbodyProblem1
    - QuickCheck
    - GLUT
    - OpenGL
