name: CI

on:
  push:
    branches: [ main ]

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Echo
      run: |
        echo "----------------------------------------------------------------------------------------\n"
        echo ${{ secrets.DOCKER_USERNAME }}
        echo "----------------------------------------------------------------------------------------\n"
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: nbodyproblem:latest

    - name: Run tests in Docker container
      run: |
        docker build . -t mamedovar/nbodyproblem:latest
#run nbodyproblem:latest sh -c "cd /app && stack test"

    - name: Login to Dockerhub
      uses: docker/login-action@v1
      with:
        username: mamedovar
        password: ${{ env.DOCKER_HUB_PASSWORD }}
      
    - name: Push image to Dockerhub
      run: |
        docker push mamedovar/nbodyproblem:latest
