name: fpco/stack-build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Haskell
      uses: haskell/actions/setup@v1
      with:
        ghc-version: '8.10.4'
    - name: Build
      run: stack build
      