name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: my-docker-image:latest

    - name: Run tests in Docker container
      run: |
        docker run my-docker-image:latest sh -c "cd /app && stack test"

        - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Push image to Dockerhub
      run: |
        docker tag my-docker-image:latest <your-dockerhub-username>/my-docker-image:latest
        docker push <your-dockerhub-username>/my-docker-image:latest
