name: Haskell CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Haskell
      uses: haskell/actions/setup@v1
      with:
        ghc-version: '8.10.4'
    - name: Install C lib
      run: sudo apt-get update && \
        sudo apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common && \
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add - && \
        add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" && \
        sudo apt-get update && \
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io
    - name: Build
      run: groupadd -g 999 docker && \
          usermod -aG docker root
