name: Haskell CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Haskell
      uses: haskell/actions/setup@v1
      with:
        ghc-version: '8.10.4'
    - name: Install C lib
      run: apt-get update && apt-get install -y \
        python3-pip \
        python3-numpy \
        libgtk2.0-dev \
        libcairo2-dev \
        libpango1.0-dev \
        libglib2.0-dev \
        libx11-dev \
        libgl1-mesa-dev \
        libglu1-mesa-dev \
        freeglut3-dev
    - name: Build
      run: stack build
      